version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "npm:"
    open-pull-requests-limit: 5
    rebase-strategy: disabled
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "ci:"
    open-pull-requests-limit: 5
    rebase-strategy: disabled
